In [1]:
import numpy as np
v=np.zeros(12)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
v[5]=1
print(v)


[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [3]:
#create a vector with values ranging from 10 to 100
b=np.arange(10,100)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [ ]:
#2D array
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [9]:
#to generate identity matrix
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
#create to random matrix of 3*3*3
d=np.random.random((3,3,3))
d

array([[[9.25458106e-01, 4.63620768e-01, 8.25005584e-04],
        [5.64387970e-01, 8.09301800e-01, 9.58160204e-01],
        [2.73715308e-02, 8.33739319e-01, 4.38995071e-01]],

       [[6.17822497e-01, 3.22754778e-01, 7.09684311e-01],
        [9.31851508e-02, 2.49805782e-01, 6.04703025e-01],
        [1.53658798e-01, 9.00782186e-01, 5.06262944e-01]],

       [[8.49781848e-01, 7.72527768e-01, 8.31626622e-01],
        [4.01256973e-01, 9.86795786e-01, 6.91419469e-01],
        [5.75201266e-01, 5.66815401e-01, 9.42791164e-01]]])

In [ ]:
#to create a 5*5 array with random value and find the maxi and mini values.
d=np.random.random((5,5))
dmin,dmax=d.min(),d.max()
print(dmin,dmax)

0.003517795462709361 0.961258794972075
